import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:file_saver/file_saver.dart';
import 'package:screenshot/screenshot.dart';

class AchievementController extends GetxController {
  static AchievementController instance = Get.find();
  late Uint8List? imageFile;
  var customText = 'Text'.obs;
  late TextEditingController filterController;
  late ScreenshotController screenshotController;

  @override
  void onInit() {
    filterController = TextEditingController();
    screenshotController = ScreenshotController();
    imageFile = Uint8List.fromList([]);
    super.onInit();
  }

  changeText(String newtext) {
    customText.value = newtext;
    notifyChildrens();
    update();
    refresh();
  }

  saveImage() async {
    await FileSaver.instance.saveFile(
        'ACHIEVEMENT GENERATED BY OMNIVERSIFY', imageFile!, 'png',
        mimeType: MimeType.PNG);
  }
/*
  @override
  void onClose() {
    //filterController.dispose();
    super.onClose();
  }*/
}
